### ISSUE TITLE
The test harness for testing net/http parsing is very slow, again

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#101]
As of Go 1.15 #59 has been become a problem again. The solution we found in #63 doesn't work. But at least we know what is causing the slowdown.`net/http.Server.Shutdown`s polling interval for checking if all connections are finished is 0.5 s and we don't have time to shut everything down before the first sleep starts. Therefore we get punished by 0.5 s every time although closing our connections takes way less than 0.5 s.

**Comment by kele** [comment]
Fixed by #274.
