### ISSUE TITLE
Add all HTTP methods that exist in net/http

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#113]
Similarly to adding all the status codes (#112) we should also add in all the HTTP methods that exists in `net/http`.

https://github.com/golang/go/blob/go1.15/src/net/http/method.go

**Comment by empijei** [comment]
Duplicate of #112 ?

**Comment by mattiasgrenfeldt** [comment]
This issue talks about HTTP methods and #112 talks about HTTP status codes. So I don't think it's a duplicate.
