### ISSUE TITLE
Proposal: implement safe HTTP client

### ISSUE THREAD

**Issue by jimen0** [google/go-safeweb#129]
## Expected Behavior

I'd like to propose to implement a safe HTTP client that applications can use with user-controlled input without being at risk of hitting unexpected hosts/endpoints. An example would be: I have a service that lets uses specify their profile picture by URL and I want to make sure I'm protected against SSRF attacks.

Note: bonus points if protection against DNS rebinding and evil redirections to internal addresses (such as metadata API) is added.

## Actual Behavior

N/A.

## Steps to Reproduce the Problem

N/A.

## Specifications

- Version: N/A
- Platform: N/A

## Problem description

I came up with a small package that does this by implementing a custom round tripper that checks against DNS rebinding and redirection attacks on each hop and run it isolated using lambda/cloudrun. However, this is a current pain I experience and I think a project like `go-safeweb` could help me fixing it.

Please, feel free to close this issue if you think the proposal isn't related to the project.

**Comment by empijei** [comment]
This is indeed a good idea but we cannot currently implement this (we would like to reach a decent feature set on the server-side part) and I am not sure this is the right place to have the client-side as well.

Thanks for reporting this!

**Comment by jimen0** [comment]
Hi @empijei,

Thanks for clarifying! I'm closing this issue now to avoid making more noise.

Best,
