### ISSUE TITLE
Status code in safehttptest.ResponseRecorder should be 0 by default instead of 200 so that interceptors that don't set it can be tested properly.

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#152]
Currently the `ResponseRecorder` in `safehttptest` sets the status code to 200 if no status code has been set yet. This should be changed to 0 so that interceptors that don't set a status code and leave it up to the handler can be tested properly.

**Comment by empijei** [comment]
I think the response recorder should behave as closely as possible to the normal serving stack. We could add one more field to check if status was automatically set, but status should behave exactly as it would when serving on the network.

**Comment by kele** [comment]
Obsoleted by #281.
