### ISSUE TITLE
Change ServeMux to write a 200 Ok response instead of 204 No Content when handler doesn't write any response to be in line with net/http.

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#153]
In #120 @empijei [suggested](https://github.com/google/go-safeweb/pull/120#discussion_r478246353) that we should respond with `200 Ok` with an empty body if a handler never writes a response instead of `204 No Content`. Responding with `200 Ok` is what `net/http` does. I missed to implement this in that PR, so I'm opening this issue.

**Comment by empijei** [comment]
I think we can close this as WAI.

I considered the options here and I'd rather keep no-content responses to have status 204 rather than 200.

@kele for one last opinion on this.

**Comment by kele** [comment]
WAI it is!
