### ISSUE TITLE
Fix interaction problems between passing a response to the safehttp.ResponseWriter writing functions that triggers an error and trying to call the markWritten function.

### ISSUE THREAD

**Issue by maramihali** [google/go-safeweb#164]
For an `safehttp.ResponseWriter w` with `safehttp.Dispatcher d`, calling `w.markWritten()` sets a boolean `w.written` that ensures a panic is triggered whenever two writing attempts are made to `w`. 

In every write function in the `safehttp.ResponseWriter` (`Write`, `WriteJSON`, `WriteTemplate`, `WriteError`, etc), `w.markWritten()` is called before attempting to retrieve the content type and dispatching the response to the `safehttp.Dispatcher`. 

This is problematic because passing an unsafe response to a writing function of `w` will trigger the following behaviour. First, `w.markWritten()` is called which will set `w.written` to `true`. Then if either `w.d.ContentType(...)` or `w.d.WriteSomething(...)` returns an error, we will panic and that will be recovered by the `ServeMux`. The` ServeMux` will then attempt to call `w.WriteError(..)` with a 500, which attempts to call `w.markWritten()` again, which will panic because `w.written` was already set to true.

This behaviour was signaled by the `TestMuxDefaultDispatcherUnsafeResponses` in integration/mux/mux_test.go that currently needs to be skipped.

We need to design a better approach to handling errors in the `safehttp.ResponseWriter` and write integration tests that thoroughly test the interaction between the `ServeMux`, `ResponseWriter` and `Dispatcher`.

**Comment by kele** [comment]
Fixed by all of the above.
