### ISSUE TITLE
Provide a way to do local development (plugins should be informed about this to change behavior)

### ISSUE THREAD

**Issue by kele** [google/go-safeweb#171]
Currently, the `xsrf` plugin sets a safe cookie with the `Secure` option, that disallows sending them over HTTP(no S). This is problematic in local development,

**Comment by empijei** [comment]
I confirm, we have to fix this, sorry about the misunderstanding, this is [specified](https://tools.ietf.org/html/rfc6265#section-4.1.2.5:~:text=An%20active%20network%20attacker%20can%20overwrite%20Secure%20cookies%20from%20an%20insecure%20channel) to also work over http.

**Comment by empijei** [comment]
We should consider exporting a global way to load up the framework in "dev" mode. Not only XSRF needs to change behavior but also the HSTS header.

This should happen before plugins are loaded, and once done it shouldn't be possible to go back to a "release" mode.
