### ISSUE TITLE
Serve a standard error response (safeHTML or template) when client-side error occurs

### ISSUE THREAD

**Issue by maramihali** [google/go-safeweb#186]
In some applications, developers want to return a (standard) error response when a client-side error occurs (either a template or an html page). We should expose a function that does that in the `safehttp.ResponseWriter`  and possibly in the `safehttp.DefaultDispatcher` as it seems a quite common functionality used. Currently, when an error occurs we just return the status code and an empty body. This "standard error response" should not, however, leak any headers that might have been set before the error was triggered so we need to clear the headers map beforehand.

**Comment by kele** [comment]
This seems to encapsulate two different issues:

1. Custom error responses are now implemented: #231.
2. Whether we should clear the headers are not is tracked at: #102.

Closing.
