### ISSUE TITLE
Simple file server (no dispatcher, no interceptors)

### ISSUE THREAD

**Issue by maramihali** [google/go-safeweb#187]
Applications frequently serve static files as a response (`.js`, `.css`, images, etc) and, for these, developers  implement unexported function to detect and set the `Content-Type`, based on the files' extension, omitting the `charset` parameter often. We might want to do this properly in the `safehttp.DefaultDispatcher`.

**Comment by kele** [comment]
Up for grabs.

How to create a relatively safe file server? Criteria:

1. 403 vs 404 error handling -> don't leak information about existence of files by responding with 403, always respond with 404.
2. Make sure that the file extension is the only thing that influences the Content-Type header (i.e. no sniffing).
3. Make sure path traversal vulns are impossible.

**Comment by kele** [comment]
We've ended up implementing a `FileServerResponse` that goes through the interceptors and the dispatcher in the end.
