### ISSUE TITLE
Support buffering the template execution for better error handling

### ISSUE THREAD

**Issue by maramihali** [google/go-safeweb#188]
A common wrong code pattern found in functions that execute and write templates to the `http.ResponseWriter` is the following:
```
w.Header().Set("Content-Type",...)
w.WriteHeader(http.StatusOK)
err := template.Execute(w, ...)
if err != nil {
    http.Error(w,...)
}
```
This won't work since, by the time an error occurs in executing the template, the headers have already been written and they cannot be modified. An alternative is to buffer the response resulted from executing the template and only write the status code and the response if all went well. Alternatively, if an error occurs, we send a `4xx` or `5xx` status code **after** any previously set header have been cleared in order to prevent any leaks. Given the security implications, maybe it would be worth to also support this in the `safehttp.DefaultDispatcher`

**Comment by kele** [comment]
I think this can be done by a custom dispatcher. I'm also not sure this should be really a native framework feature.

@empijei WDYT?

**Comment by empijei** [comment]
I don't think this belongs to the framework. It is trivial to build a standalone helper that does that and either call that or put it inside the dispatcher.

I would stay away from adding a default that thrashes the GC, and if we don't make this the default we can just provide a helper function in the future.
