### ISSUE TITLE
Clear headers map in safehttp.ResponseWriter.WriteError

### ISSUE THREAD

**Issue by maramihali** [google/go-safeweb#189]
In order to prevent leaks when an error occurs, we need to ensure the headers map is cleared before calling `http.Error` in the `safehttp.ResponseWriter.WriteError` funciton.

**Comment by kele** [comment]
Why?

**Comment by maramihali** [comment]
Currently, if some interceptor or handler sets a `SecretHeader` and then an error occurs, the `SecretHeader` will still still be sent. We want to prevent this, don't we?

**Comment by kele** [comment]
Could you come up with a compelling example on why we'd want that? Also, it is quite important here to distinguish when the header is set (e.g. if you set your header in `Before()`, is it really that secret?).

**Comment by kele** [comment]
This is actually a duplicate of #102.
