### ISSUE TITLE
Document strange parsing behavior

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#23]
To document the strange behavior we (@mattiasgrenfeldt and @mihalimara22) have found while testing the current behavior of `net/http` in #5 and #6 we should do the following: For each behavior we have observed that is strange or undesirable we should:

- Create a separate test function that tests this behavior.
- Create one subtest in the function that documents the **current** behavior.
- Create one subtest in the function that documents the **desired** behavior. Use `t.Skip()` so that the tests pass CI.
- Document the behavior using comments and explain why it is strange or undesirable.

(Issue created on @kele 's request.)

**Comment by kele** [comment]
AFAIR this has been resolved. 

Example: https://github.com/google/go-safeweb/blob/5bf9c9c450a7394bb45ba765bf0e266fb11e59ce/tests/headers/host_test.go#L141.
