### ISSUE TITLE
Mismatch between the directory name and package name of the Fetch Metadata plugin

### ISSUE THREAD

**Issue by kele** [google/go-safeweb#232]
Currently it has to be imported like this:

```
import fetchmetadata "github.com/google/go-safeweb/safehttp/plugins/fetch_metadata"
```

**Comment by mikue1** [comment]
If I understand correctly, this issue is basically about renaming the folder `plugins/fetch_metadata` to `plugins/fetchmetadata` (and possible the related .go files)? I can send a PR for that.

**Comment by kele** [comment]
Yup.
