### ISSUE TITLE
xsrfangular might be vulnerable to BREACH attack

### ISSUE THREAD

**Issue by empijei** [google/go-safeweb#234]
We should probably check if http://breachattack.com/ might allow an attacker to guess the angular CSRF token and, if so, try to understand how to mitigate this and still have a library that seamlessly integrates with Angular.

**Comment by empijei** [comment]
After a quick looks it seems fine: the token is never injected in the context nor in the template so it never appears in the response, hence should not be vulnerable to attacks that rely on body compression.

**Comment by kele** [comment]
What about `xsrfhtml` then?

**Comment by empijei** [comment]
xsrfhtml generates a new token for every response because tokens are bound to the current time. BREACH only applies if the token is the same in every response.
