### ISSUE TITLE
Provide a way for the dispatcher to extract the request for the given flight

### ISSUE THREAD

**Issue by empijei** [google/go-safeweb#313]
In many cases, mainly for library re-use, it would be very useful to have a reference to the `*http.Request` for the current flight to allow calls into pre-existing dependencies.

**Comment by kele** [comment]
Discussed offline.

Implement a `safehttp/restricted` package using tricks similar to `safesql/uncheckedconversions` that allows extracting `*http.Request` from the `safehttp.IncomingRequest`. This package should be used exclusively by the security team in an organization, and can be useful e.g. in the `Dispatcher`.

**Comment by kele** [comment]
Fixed by #325.

https://github.com/google/go-safeweb/pull/325/files#diff-2bc8bf14857fb31ffda84724e140386504137d2ef0c6dba29230c505b96ca4e7
