### ISSUE TITLE
SetContext violates the context.Context contract

### ISSUE THREAD

**Issue by empijei** [google/go-safeweb#314]
In all APIs that rely on context there is no way for a callee to change the context of the caller.

Our IncomingRequest.SetContext method allows to do that. We should instead mimic the stdlib way and clone the request.

Alternatively we could explicitly pass context.Context as first parameter, but it would be quite a bit leap from the stlib api.

**Comment by kele** [comment]
I'm in favor of cloning as it's done in `net/http`.

**Comment by kele** [comment]
https://github.com/google/go-safeweb/pull/321 switches `SetContext` to `WithContext`.
