### ISSUE TITLE
Re-assess the one-config-per-interceptor hard limit

### ISSUE THREAD

**Issue by empijei** [google/go-safeweb#318]
Currently having multiple configurations match an interceptor causes a panic at registration time.

We might want to re-assess this limit.

There are two alternatives:
* We could have interceptors take a slice of configs, but this would make interceptors quite a bit more complicated for a very rare use case
* We can say that if two configurations match, but at least one of them has a `Merge(InterceptorConfig)` method on it, we call that method and use what is returned as a configuration

**Comment by kele** [comment]
What's a real world use case here?

**Comment by empijei** [comment]
Discussed offline:

This would enable very complicated things that should probably be done at the interceptor level and not at the framework level.
