### ISSUE TITLE
Handling boolean form values

### ISSUE THREAD

**Issue by mihalimara22** [google/go-safeweb#35]
Currently, we consider valid booleans to be only  the strings `"true"` and `"false"`, unlike `strconv.ParseBool()` which correctly converts `"1", "t", "T", "true", "TRUE", "True", "0", "f", "F", "false", "FALSE", "False"` into `bool`. We should discuss the implications of this and decide whether we want to use `strconv.ParseBool()` in the `safehttp.Form` implementation.

**Comment by empijei** [comment]
I am in favor of using whatever ParseBool uses. @kele ?

**Comment by mattiasgrenfeldt** [comment]
I'll implement this. (I got @mihalimara22 's permisson)
