### ISSUE TITLE
Test failure with upcoming Go 1.20 release

### ISSUE THREAD

**Issue by ianlancetaylor** [google/go-safeweb#350]
## Expected Behavior

`cd internal/requesttesting/header && go test` passes.

## Actual Behavior

```
--- FAIL: TestStatusCode (0.00s)
    --- FAIL: TestStatusCode/UnicodeHeaderName (0.00s)
        header_test.go:194: status code got: "HTTP/1.1 400 Bad Request" want: "HTTP/1.1 400 Bad Request: invalid header name"
    --- FAIL: TestStatusCode/SpecialCharactersHeaderName (0.00s)
        header_test.go:194: status code got: "HTTP/1.1 400 Bad Request" want: "HTTP/1.1 400 Bad Request: invalid header name"
    --- FAIL: TestStatusCode/NullByteInHeaderName (0.00s)
        header_test.go:194: status code got: "HTTP/1.1 400 Bad Request" want: "HTTP/1.1 400 Bad Request: invalid header name"
    --- FAIL: TestStatusCode/NullByteInHeaderValue (0.00s)
        header_test.go:194: status code got: "HTTP/1.1 400 Bad Request" want: "HTTP/1.1 400 Bad Request: invalid header value"
FAIL
exit status 1
FAIL	github.com/google/go-safeweb/internal/requesttesting/headers	0.008s
```

This appears to have broken due to https://go.dev/cl/410714 which was for https://go.dev/issue/53188.  Note that the request still fails; it just reports a different error status.

## Steps to Reproduce the Problem

1. build the Go release at HEAD, which will be the future Go 1.20 release.
1. cd internal/requesttesting/headers
1. go test

## Specifications

- Version: go-safeweb version babe3ab1de3d79bc4674352241f2a9d0634b0362, Go version devel go1.20-793f1a13f7
- Platform: x86_64 Linux

**Comment by aktau** [comment]
The failure is a mismatch in error messages, but the upstream behaviour is also lightly changed (rejecting more requests). From the README:

> HTTP Request Parsing Bugs - e.g. by implementing strict and well documented parsing behavior

It's not far to make the assumption the safeweb already implemented the behaviour that's now upstream, meaning there's no change in behaviour due to this upstream change for safeweb users. Would that be correct?

**Comment by empijei** [comment]
I concur that the behavior of rejecting more is better, and I relaxed the tests to validate that we reject with the expected status, not the expected status message.

**Comment by ianlancetaylor** [comment]
Thanks!
