### ISSUE TITLE
Support header claiming as a means of expressing ownership of (security-sensitive) headers

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#44]
Plugins might need to mark a header as immutable and then change it at a later stage. A method called `Claim` will therefore be implemented that sets the header as immutable and returns something that can later change the header. When `Claim` is implemented there will be no need for `MarkImmutable` (for now) and therefore it will be removed.

**Comment by mattiasgrenfeldt** [comment]
Should we also remove the `SetCookie` function? I think so. What do you think: @mihalimara22 @kele @empijei ?

**Comment by mattiasgrenfeldt** [comment]
I still want to discuss this. Should we also remove the `SetCookie` function? I think so. What do you think: @mihalimara22 @kele @empijei ?

**Comment by kele** [comment]
Please file a separate issue to figure out how to support safe cookie handling.
