### ISSUE TITLE
The test harness for testing net/http parsing is very slow

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#59]
Running the tests in `tests/headers`, `tests/formparams` and `tests/queryparams` currently takes 30+ seconds. This is **very** slow. They all use the testing harness in `internal/requesttesting/test_harness.go`. @empijei suspects that this might be because something is not closed correctly which causes the test harness to have to wait for a timeout to finish on each test.

This needs to be investigated further. The cause of the slowdown needs to identified and fixed.

**Comment by empijei** [comment]
This is still true with latest go. We should really find a proper fix for this, or mark some tests as slow and not run them by default.
