### ISSUE TITLE
Add template nonce injection

### ISSUE THREAD

**Issue by empijei** [google/go-safeweb#76]
The CSP and XSRF plugins currently put tokens in the request context.

* There needs to be a part of the plugins that can, later on, provide that nonce for a template to render.
* This should ideally work easily with different template implementations
* This will likely happen in the Commit phase of both plugins

**Comment by mattiasgrenfeldt** [comment]
I would say that this is fixed since the CSP plugin has the `Nonce` function which can provide the nonce for a template to use.

Here is the Nonce method: https://github.com/google/go-safeweb/blob/master/safehttp/plugins/csp/csp.go#L54-L62
